# Generated by Django 5.2.6 on 2025-11-03 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDailyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.FloatField()),
                ('ending', models.FloatField()),
                ('date', models.DateField()),
                ('STOCK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stock_table')),
            ],
        ),
    ]
